### ISSUE TITLE
AttributeError: module 'pytessy' has no attribute 'PyTessy'

### ISSUE THREAD

**Issue by ishandutta2007** [hyperrixel/pytessy#4]
`pip3 install pytessy`

```
import pytessy
from PIL import ImageFilter, Image
ocrReader = pytessy.PyTessy()
```

> 
> C:\Users\hp\Documents\Projects\ExtractImageLoc>python pytessy.py
> Traceback (most recent call last):
>   File "pytessy.py", line 2, in <module>
>     import pytessy
>   File "C:\Users\hp\Documents\Projects\ExtractImageLoc\pytessy.py", line 11, in <module>
>     ocrReader = pytessy.PyTessy()
> AttributeError: module 'pytessy' has no attribute 'PyTessy'

**Comment by ishandutta2007** [comment]
When I cloned the [repo ](https://github.com/tbattz/pytessy)and ran the [example ](https://github.com/tbattz/pytessy/blob/master/exampleUsage.py)where it imports from source directory instead of the installed package, I faced another issue.
```

from source import pytessy
from PIL import ImageFilter, Image
ocrReader = pytessy.PyTessy()

```

> FileNotFoundError: Cannot locate Tesseract-OCR library.


Then I changed it to
```
ocrReader = pytessy.PyTessy(lib_path="C:/Program Files/Tesseract-OCR")
```

> FileNotFoundError: PyTessy: lib_path: "C:/Program Files/Tesseract-OCR" doesn't exist.

also tried
```
ocrReader = pytessy.PyTessy(lib_path="C:/Program Files/Tesseract-OCR/tesseract")
```

> FileNotFoundError: PyTessy: lib_path: "C:/Program Files/Tesseract-OCR/tesseract" doesn't exist.

@tbattz I am windows, it shouldn't be too different, help please :)

**Comment by tbattz** [comment]
> When I cloned the [repo ](https://github.com/tbattz/pytessy)and ran the [example ](https://github.com/tbattz/pytessy/blob/master/exampleUsage.py)where it imports from source directory instead of the installed package, I faced another issue.
> 
> ```
> 
> from source import pytessy
> from PIL import ImageFilter, Image
> ocrReader = pytessy.PyTessy()
> ```
> 
> > FileNotFoundError: Cannot locate Tesseract-OCR library.
> 
> Then I changed it to
> 
> ```
> ocrReader = pytessy.PyTessy(lib_path="C:/Program Files/Tesseract-OCR")
> ```
> 
> > FileNotFoundError: PyTessy: lib_path: "C:/Program Files/Tesseract-OCR" doesn't exist.
> 
> also tried
> 
> ```
> ocrReader = pytessy.PyTessy(lib_path="C:/Program Files/Tesseract-OCR/tesseract")
> ```
> 
> > FileNotFoundError: PyTessy: lib_path: "C:/Program Files/Tesseract-OCR/tesseract" doesn't exist.
> 
> @tbattz I am windows, it shouldn't be too different, help please :)

@ishandutta2007 Initially I tried downloading the old version (V3.02) of tesseract from the bottom of this page: https://tesseract-ocr.github.io/tessdoc/Downloads.html

That didn't work, but it gave the path you were trying.

Uninstalling that, and downloading V5 from https://github.com/UB-Mannheim/tesseract/wiki, and it works without specifying a path, so give that a try.

**Comment by ishandutta2007** [comment]
> Uninstalling that, and downloading V5 from https://github.com/UB-Mannheim/tesseract/wiki, and it works without specifying a path, so give that a try.

I am using v5 alpha only. My exe file name is `tesseract-ocr-w64-setup-v5.0.0-alpha.20201127`

Anyways nevermind your case might be different as you are on linux, it seems being on windows is the root of all issues, will try on linux when I have access to one.

**Comment by tbattz** [comment]
> > Uninstalling that, and downloading V5 from https://github.com/UB-Mannheim/tesseract/wiki, and it works without specifying a path, so give that a try.
> 
> I am using v5 alpha only. My exe file name is `tesseract-ocr-w64-setup-v5.0.0-alpha.20201127`
> 
> Anyways nevermind your case might be different as you are on linux, it seems being on windows is the root of all issues, will try on linux when I have access to one.

That was on Windows, but I think if you look in the pytessy script, lib_path narrows down the search to dll files, for me it finds libtesseract-5.dll, so that's what you'd want within the directory of the path you give it.

**Comment by MatejVitek** [comment]
> `pip3 install pytessy`
> 
> ```
> import pytessy
> from PIL import ImageFilter, Image
> ocrReader = pytessy.PyTessy()
> ```
> 
> > C:\Users\hp\Documents\Projects\ExtractImageLoc>python pytessy.py
> > Traceback (most recent call last):
> > File "pytessy.py", line 2, in 
> > import pytessy
> > File "C:\Users\hp\Documents\Projects\ExtractImageLoc\pytessy.py", line 11, in 
> > ocrReader = pytessy.PyTessy()
> > AttributeError: module 'pytessy' has no attribute 'PyTessy'

This importing from the `pytessy` package, not the `pytessy` module (which is actually `pytessy.pytessy`). So with the pip-installed versioned you should use:

    from pytessy.pytessy import PyTessy
    ocrReader = PyTessy(...)

or

    from pytessy import pytessy
    ocrReader = pytessy.PyTessy(...)

**Comment by ishandutta2007** [comment]
@tbattz Acctually I moved away from using pytessy to easyocr. So can't really give you an update on this. [easyocr](https://github.com/JaidedAI/EasyOCR) internally uses Terraract too. So it must be issue on pytessy's side.
